### ISSUE TITLE
Meesed up tracks in Godot 3.4.

### ISSUE THREAD

**Issue by IvailoBurov** [BastiaanOlij/vehicle-demo#13]
Hi,
Seems there are any changes in Godot 3.4 that make many displacements in roads with CSGPolygon. PoolVector2Arr properties do not correspond to those of version 3.3.
In my project I failed to change them so that they work properly as with version 3.3, which makes the whole technique useless. Also, textures cannot be stretched properly.
I opened your projects and here I see a big discrepancy. I am sending two screenshots: with version 3.3 and 3.4.
 
![Vahicle3 3](https://user-images.githubusercontent.com/63282037/154728640-3b55fb4f-cb8f-4333-a776-fb67ec71af13.png)

![Vehicle 3 4 2](https://user-images.githubusercontent.com/63282037/154728697-1186663f-4969-4d0b-afa3-1c5bc5ed0c05.png)

**Comment by BastiaanOlij** [comment]
Indeed, I haven't gotten around to update the demo though I did play around with it. There were a number of breaking changes in CSGPolygon in 3.4 including one or two that caused a bit of a storm in the community (basically at some point we couldn't even make tracks anymore because someone had overlooked this usecase). The end result however is a far superior implementation that even optimises the polygon count on the track.

However it requires changing some of the new settings. I'll see if I can soon find a minute to update the project.

**Comment by IvailoBurov** [comment]
Thanks for the answer and the hard work in creating the training videos.
There is also a problem with overlapping textures. They appear behind those with lower priority when rendering. To my great surprise, today I discovered that the coordinates of placed objects with version 3.4 differ from those when the project opened with version 3.3 and vice versa.

**Comment by BastiaanOlij** [comment]
Fixed by #14
